//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace AdventureWorksSL.ProductCatalogServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/AdventureWorks.Domain.ModelObjects.DataTr" +
        "ansfer", IsReference=true)]
    public partial class Product : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ClassField;
        
        private string ColorField;
        
        private int DaysToManufactureField;
        
        private System.Nullable<System.DateTime> DiscontinuedDateField;
        
        private bool FinishedGoodsFlagField;
        
        private decimal ListPriceField;
        
        private bool MakeFlagField;
        
        private string NameField;
        
        private int ProductIDField;
        
        private System.Collections.ObjectModel.ObservableCollection<AdventureWorksSL.ProductCatalogServiceReference.ProductInventory> ProductInventoriesField;
        
        private string ProductLineField;
        
        private System.Nullable<int> ProductModelIDField;
        
        private string ProductNumberField;
        
        private System.Nullable<int> ProductSubcategoryIDField;
        
        private short ReorderPointField;
        
        private short SafetyStockLevelField;
        
        private System.Nullable<System.DateTime> SellEndDateField;
        
        private System.DateTime SellStartDateField;
        
        private string SizeField;
        
        private string SizeUnitMeasureCodeField;
        
        private decimal StandardCostField;
        
        private string StyleField;
        
        private System.Nullable<decimal> WeightField;
        
        private string WeightUnitMeasureCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class {
            get {
                return this.ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassField, value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DaysToManufacture {
            get {
                return this.DaysToManufactureField;
            }
            set {
                if ((this.DaysToManufactureField.Equals(value) != true)) {
                    this.DaysToManufactureField = value;
                    this.RaisePropertyChanged("DaysToManufacture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DiscontinuedDate {
            get {
                return this.DiscontinuedDateField;
            }
            set {
                if ((this.DiscontinuedDateField.Equals(value) != true)) {
                    this.DiscontinuedDateField = value;
                    this.RaisePropertyChanged("DiscontinuedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FinishedGoodsFlag {
            get {
                return this.FinishedGoodsFlagField;
            }
            set {
                if ((this.FinishedGoodsFlagField.Equals(value) != true)) {
                    this.FinishedGoodsFlagField = value;
                    this.RaisePropertyChanged("FinishedGoodsFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ListPrice {
            get {
                return this.ListPriceField;
            }
            set {
                if ((this.ListPriceField.Equals(value) != true)) {
                    this.ListPriceField = value;
                    this.RaisePropertyChanged("ListPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MakeFlag {
            get {
                return this.MakeFlagField;
            }
            set {
                if ((this.MakeFlagField.Equals(value) != true)) {
                    this.MakeFlagField = value;
                    this.RaisePropertyChanged("MakeFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<AdventureWorksSL.ProductCatalogServiceReference.ProductInventory> ProductInventories {
            get {
                return this.ProductInventoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductInventoriesField, value) != true)) {
                    this.ProductInventoriesField = value;
                    this.RaisePropertyChanged("ProductInventories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductLine {
            get {
                return this.ProductLineField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductLineField, value) != true)) {
                    this.ProductLineField = value;
                    this.RaisePropertyChanged("ProductLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProductModelID {
            get {
                return this.ProductModelIDField;
            }
            set {
                if ((this.ProductModelIDField.Equals(value) != true)) {
                    this.ProductModelIDField = value;
                    this.RaisePropertyChanged("ProductModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductNumber {
            get {
                return this.ProductNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNumberField, value) != true)) {
                    this.ProductNumberField = value;
                    this.RaisePropertyChanged("ProductNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProductSubcategoryID {
            get {
                return this.ProductSubcategoryIDField;
            }
            set {
                if ((this.ProductSubcategoryIDField.Equals(value) != true)) {
                    this.ProductSubcategoryIDField = value;
                    this.RaisePropertyChanged("ProductSubcategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ReorderPoint {
            get {
                return this.ReorderPointField;
            }
            set {
                if ((this.ReorderPointField.Equals(value) != true)) {
                    this.ReorderPointField = value;
                    this.RaisePropertyChanged("ReorderPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short SafetyStockLevel {
            get {
                return this.SafetyStockLevelField;
            }
            set {
                if ((this.SafetyStockLevelField.Equals(value) != true)) {
                    this.SafetyStockLevelField = value;
                    this.RaisePropertyChanged("SafetyStockLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SellEndDate {
            get {
                return this.SellEndDateField;
            }
            set {
                if ((this.SellEndDateField.Equals(value) != true)) {
                    this.SellEndDateField = value;
                    this.RaisePropertyChanged("SellEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SellStartDate {
            get {
                return this.SellStartDateField;
            }
            set {
                if ((this.SellStartDateField.Equals(value) != true)) {
                    this.SellStartDateField = value;
                    this.RaisePropertyChanged("SellStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Size {
            get {
                return this.SizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeField, value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SizeUnitMeasureCode {
            get {
                return this.SizeUnitMeasureCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeUnitMeasureCodeField, value) != true)) {
                    this.SizeUnitMeasureCodeField = value;
                    this.RaisePropertyChanged("SizeUnitMeasureCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StandardCost {
            get {
                return this.StandardCostField;
            }
            set {
                if ((this.StandardCostField.Equals(value) != true)) {
                    this.StandardCostField = value;
                    this.RaisePropertyChanged("StandardCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Style {
            get {
                return this.StyleField;
            }
            set {
                if ((object.ReferenceEquals(this.StyleField, value) != true)) {
                    this.StyleField = value;
                    this.RaisePropertyChanged("Style");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WeightUnitMeasureCode {
            get {
                return this.WeightUnitMeasureCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WeightUnitMeasureCodeField, value) != true)) {
                    this.WeightUnitMeasureCodeField = value;
                    this.RaisePropertyChanged("WeightUnitMeasureCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductInventory", Namespace="http://schemas.datacontract.org/2004/07/AdventureWorks.Domain.ModelObjects.DataTr" +
        "ansfer", IsReference=true)]
    public partial class ProductInventory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte BinField;
        
        private short LocationIDField;
        
        private int ProductIDField;
        
        private short QuantityField;
        
        private string ShelfField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Bin {
            get {
                return this.BinField;
            }
            set {
                if ((this.BinField.Equals(value) != true)) {
                    this.BinField = value;
                    this.RaisePropertyChanged("Bin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short LocationID {
            get {
                return this.LocationIDField;
            }
            set {
                if ((this.LocationIDField.Equals(value) != true)) {
                    this.LocationIDField = value;
                    this.RaisePropertyChanged("LocationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shelf {
            get {
                return this.ShelfField;
            }
            set {
                if ((object.ReferenceEquals(this.ShelfField, value) != true)) {
                    this.ShelfField = value;
                    this.RaisePropertyChanged("Shelf");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductCatalogServiceReference.IProductCatalogService")]
    public interface IProductCatalogService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IProductCatalogService/GetProductList", ReplyAction="http://tempuri.org/IProductCatalogService/GetProductListResponse")]
        System.IAsyncResult BeginGetProductList(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<AdventureWorksSL.ProductCatalogServiceReference.Product> EndGetProductList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IProductCatalogService/GetProductDetail", ReplyAction="http://tempuri.org/IProductCatalogService/GetProductDetailResponse")]
        System.IAsyncResult BeginGetProductDetail(int id, System.AsyncCallback callback, object asyncState);
        
        AdventureWorksSL.ProductCatalogServiceReference.Product EndGetProductDetail(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductCatalogServiceChannel : AdventureWorksSL.ProductCatalogServiceReference.IProductCatalogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetProductListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProductListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<AdventureWorksSL.ProductCatalogServiceReference.Product> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<AdventureWorksSL.ProductCatalogServiceReference.Product>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetProductDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProductDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AdventureWorksSL.ProductCatalogServiceReference.Product Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AdventureWorksSL.ProductCatalogServiceReference.Product)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductCatalogServiceClient : System.ServiceModel.ClientBase<AdventureWorksSL.ProductCatalogServiceReference.IProductCatalogService>, AdventureWorksSL.ProductCatalogServiceReference.IProductCatalogService {
        
        private BeginOperationDelegate onBeginGetProductListDelegate;
        
        private EndOperationDelegate onEndGetProductListDelegate;
        
        private System.Threading.SendOrPostCallback onGetProductListCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetProductDetailDelegate;
        
        private EndOperationDelegate onEndGetProductDetailDelegate;
        
        private System.Threading.SendOrPostCallback onGetProductDetailCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ProductCatalogServiceClient() {
        }
        
        public ProductCatalogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductCatalogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductCatalogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductCatalogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetProductListCompletedEventArgs> GetProductListCompleted;
        
        public event System.EventHandler<GetProductDetailCompletedEventArgs> GetProductDetailCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AdventureWorksSL.ProductCatalogServiceReference.IProductCatalogService.BeginGetProductList(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProductList(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<AdventureWorksSL.ProductCatalogServiceReference.Product> AdventureWorksSL.ProductCatalogServiceReference.IProductCatalogService.EndGetProductList(System.IAsyncResult result) {
            return base.Channel.EndGetProductList(result);
        }
        
        private System.IAsyncResult OnBeginGetProductList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((AdventureWorksSL.ProductCatalogServiceReference.IProductCatalogService)(this)).BeginGetProductList(callback, asyncState);
        }
        
        private object[] OnEndGetProductList(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<AdventureWorksSL.ProductCatalogServiceReference.Product> retVal = ((AdventureWorksSL.ProductCatalogServiceReference.IProductCatalogService)(this)).EndGetProductList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProductListCompleted(object state) {
            if ((this.GetProductListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProductListCompleted(this, new GetProductListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProductListAsync() {
            this.GetProductListAsync(null);
        }
        
        public void GetProductListAsync(object userState) {
            if ((this.onBeginGetProductListDelegate == null)) {
                this.onBeginGetProductListDelegate = new BeginOperationDelegate(this.OnBeginGetProductList);
            }
            if ((this.onEndGetProductListDelegate == null)) {
                this.onEndGetProductListDelegate = new EndOperationDelegate(this.OnEndGetProductList);
            }
            if ((this.onGetProductListCompletedDelegate == null)) {
                this.onGetProductListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProductListCompleted);
            }
            base.InvokeAsync(this.onBeginGetProductListDelegate, null, this.onEndGetProductListDelegate, this.onGetProductListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AdventureWorksSL.ProductCatalogServiceReference.IProductCatalogService.BeginGetProductDetail(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProductDetail(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdventureWorksSL.ProductCatalogServiceReference.Product AdventureWorksSL.ProductCatalogServiceReference.IProductCatalogService.EndGetProductDetail(System.IAsyncResult result) {
            return base.Channel.EndGetProductDetail(result);
        }
        
        private System.IAsyncResult OnBeginGetProductDetail(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return ((AdventureWorksSL.ProductCatalogServiceReference.IProductCatalogService)(this)).BeginGetProductDetail(id, callback, asyncState);
        }
        
        private object[] OnEndGetProductDetail(System.IAsyncResult result) {
            AdventureWorksSL.ProductCatalogServiceReference.Product retVal = ((AdventureWorksSL.ProductCatalogServiceReference.IProductCatalogService)(this)).EndGetProductDetail(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProductDetailCompleted(object state) {
            if ((this.GetProductDetailCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProductDetailCompleted(this, new GetProductDetailCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProductDetailAsync(int id) {
            this.GetProductDetailAsync(id, null);
        }
        
        public void GetProductDetailAsync(int id, object userState) {
            if ((this.onBeginGetProductDetailDelegate == null)) {
                this.onBeginGetProductDetailDelegate = new BeginOperationDelegate(this.OnBeginGetProductDetail);
            }
            if ((this.onEndGetProductDetailDelegate == null)) {
                this.onEndGetProductDetailDelegate = new EndOperationDelegate(this.OnEndGetProductDetail);
            }
            if ((this.onGetProductDetailCompletedDelegate == null)) {
                this.onGetProductDetailCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProductDetailCompleted);
            }
            base.InvokeAsync(this.onBeginGetProductDetailDelegate, new object[] {
                        id}, this.onEndGetProductDetailDelegate, this.onGetProductDetailCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override AdventureWorksSL.ProductCatalogServiceReference.IProductCatalogService CreateChannel() {
            return new ProductCatalogServiceClientChannel(this);
        }
        
        private class ProductCatalogServiceClientChannel : ChannelBase<AdventureWorksSL.ProductCatalogServiceReference.IProductCatalogService>, AdventureWorksSL.ProductCatalogServiceReference.IProductCatalogService {
            
            public ProductCatalogServiceClientChannel(System.ServiceModel.ClientBase<AdventureWorksSL.ProductCatalogServiceReference.IProductCatalogService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetProductList(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetProductList", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<AdventureWorksSL.ProductCatalogServiceReference.Product> EndGetProductList(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<AdventureWorksSL.ProductCatalogServiceReference.Product> _result = ((System.Collections.ObjectModel.ObservableCollection<AdventureWorksSL.ProductCatalogServiceReference.Product>)(base.EndInvoke("GetProductList", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetProductDetail(int id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("GetProductDetail", _args, callback, asyncState);
                return _result;
            }
            
            public AdventureWorksSL.ProductCatalogServiceReference.Product EndGetProductDetail(System.IAsyncResult result) {
                object[] _args = new object[0];
                AdventureWorksSL.ProductCatalogServiceReference.Product _result = ((AdventureWorksSL.ProductCatalogServiceReference.Product)(base.EndInvoke("GetProductDetail", _args, result)));
                return _result;
            }
        }
    }
}
