//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorks.Domain.ModelObjects.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
    
    [DataContract]
    public partial class Product
    {
        public Product()
        {
            this.BillOfMaterials = new HashSet<BillOfMaterial>();
            this.BillOfMaterials1 = new HashSet<BillOfMaterial>();
            this.ProductCostHistories = new HashSet<ProductCostHistory>();
            this.ProductInventories = new HashSet<ProductInventory>();
            this.ProductListPriceHistories = new HashSet<ProductListPriceHistory>();
            this.ProductProductPhotoes = new HashSet<ProductProductPhoto>();
            this.ProductReviews = new HashSet<ProductReview>();
            this.ProductVendors = new HashSet<ProductVendor>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
            this.ShoppingCartItems = new HashSet<ShoppingCartItem>();
            this.SpecialOfferProducts = new HashSet<SpecialOfferProduct>();
            this.TransactionHistories = new HashSet<TransactionHistory>();
            this.WorkOrders = new HashSet<WorkOrder>();
        }
    
        [DataMember]
        public int ProductID { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        [Display(Name = "Product Number")]
        public string ProductNumber { get; set; }
        [DataMember]
        [Display(Name = "Make Flag")]
        public bool MakeFlag { get; set; }
        [DataMember]
        [Display(Name = "Finished Goods Flag")]
        public bool FinishedGoodsFlag { get; set; }
        [DataMember]
        public string Color { get; set; }
        [DataMember]
        [Display(Name = "Safety Stock Level")]
        public short SafetyStockLevel { get; set; }
        [DataMember]
        [Display(Name = "Reorder Point")]
        public short ReorderPoint { get; set; }
        [DataMember]
        [Display(Name = "Standard Cost")]
        public decimal StandardCost { get; set; }
        [DataMember]
        [Display(Name = "List Price")]
        public decimal ListPrice { get; set; }
        [DataMember]
        public string Size { get; set; }
        [DataMember]
        [Display(Name = "Size Unit")]
        public string SizeUnitMeasureCode { get; set; }
        [DataMember]
        [Display(Name = "Weight Unit")]
        public string WeightUnitMeasureCode { get; set; }
        [DataMember]
        public Nullable<decimal> Weight { get; set; }
        [DataMember]
        [Display(Name = "Days to Manufacture")]
        public int DaysToManufacture { get; set; }
        [DataMember]
        [Display(Name = "Product Line")]
        public string ProductLine { get; set; }
        [DataMember]
        public string Class { get; set; }
        [DataMember]
        public string Style { get; set; }
        [DataMember]
        [Display(Name = "Product Subcategory ID")]
        public Nullable<int> ProductSubcategoryID { get; set; }
        [DataMember]
        [Display(Name = "Model ID")]
        public Nullable<int> ProductModelID { get; set; }
        [DataMember]
        [Display(Name = "Sell Start Date")]
        public System.DateTime SellStartDate { get; set; }
        [DataMember]
        [Display(Name = "Sell End Date")]
        public Nullable<System.DateTime> SellEndDate { get; set; }
        [DataMember]
        [Display(Name = "Discontinued Date")]
        public Nullable<System.DateTime> DiscontinuedDate { get; set; }
        [DataMember]
        public System.Guid rowguid { get; set; }
        [DataMember]
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<BillOfMaterial> BillOfMaterials { get; set; }
        public virtual ICollection<BillOfMaterial> BillOfMaterials1 { get; set; }
        public virtual ProductModel ProductModel { get; set; }
        public virtual ProductSubcategory ProductSubcategory { get; set; }
        public virtual UnitMeasure UnitMeasure { get; set; }
        public virtual UnitMeasure UnitMeasure1 { get; set; }
        public virtual ICollection<ProductCostHistory> ProductCostHistories { get; set; }
        public virtual ProductDocument ProductDocument { get; set; }
        public virtual ICollection<ProductInventory> ProductInventories { get; set; }
        public virtual ICollection<ProductListPriceHistory> ProductListPriceHistories { get; set; }
        public virtual ICollection<ProductProductPhoto> ProductProductPhotoes { get; set; }
        public virtual ICollection<ProductReview> ProductReviews { get; set; }
        public virtual ICollection<ProductVendor> ProductVendors { get; set; }
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual ICollection<ShoppingCartItem> ShoppingCartItems { get; set; }
        public virtual ICollection<SpecialOfferProduct> SpecialOfferProducts { get; set; }
        public virtual ICollection<TransactionHistory> TransactionHistories { get; set; }
        public virtual ICollection<WorkOrder> WorkOrders { get; set; }
    }
}
