//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorks.Domain.ModelObjects.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;

    [DataContract]
    public partial class ProductVendor
    {
        [DataMember]
        public int ProductID { get; set; }
        [DataMember]
        public int BusinessEntityID { get; set; }
        [DataMember]
        [Display(Name = "Avg Lead Time")]
        public int AverageLeadTime { get; set; }
        [DataMember]
        [Display(Name = "Standard Price")]
        public decimal StandardPrice { get; set; }
        [DataMember]
        [Display(Name = "Last Receipt Cost")]
        public Nullable<decimal> LastReceiptCost { get; set; }
        [DataMember]
        [Display(Name = "Last Receipt Date")]
        public Nullable<System.DateTime> LastReceiptDate { get; set; }
        [DataMember]
        [Display(Name = "Min Order Qty")]
        public int MinOrderQty { get; set; }
        [DataMember]
        [Display(Name = "Max Order Qty")]
        public int MaxOrderQty { get; set; }
        [DataMember]
        [Display(Name = "On Order Qty")]
        public Nullable<int> OnOrderQty { get; set; }
        [DataMember]
        [Display(Name = "Unit Measure Code")]
        public string UnitMeasureCode { get; set; }
        public System.DateTime ModifiedDate { get; set; }

        [DataMember]
        public virtual Product Product { get; set; }
        [DataMember]
        public virtual UnitMeasure UnitMeasure { get; set; }
        [DataMember]
        public virtual Vendor Vendor { get; set; }
    }
}
