//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorks.Domain.ModelObjects.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
    
    [DataContract]
    public partial class SalesOrderHeader
    {
        public SalesOrderHeader()
        {
            this.SalesOrderDetails = new HashSet<SalesOrderDetail>();
            this.SalesOrderHeaderSalesReasons = new HashSet<SalesOrderHeaderSalesReason>();
        }
    
        [DataMember]
        public int SalesOrderID { get; set; }
        [DataMember]
        [Display(Name = "Revision Number")]
        public byte RevisionNumber { get; set; }
        [DataMember]
        [Display(Name = "Order Date")]
        public System.DateTime OrderDate { get; set; }
        [DataMember]
        [Display(Name = "Due Date")]
        public System.DateTime DueDate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ShipDate { get; set; }
        [DataMember]
        public byte Status { get; set; }
        [DataMember]
        [Display(Name = "Online Order Flag")]
        public bool OnlineOrderFlag { get; set; }
        [DataMember]
        [Display(Name = "Sales Order Number")]
        public string SalesOrderNumber { get; set; }
        [DataMember]
        [Display(Name = "PO Number")]
        public string PurchaseOrderNumber { get; set; }
        [DataMember]
        [Display(Name = "Account Number")]
        public string AccountNumber { get; set; }
        [DataMember]
        public int CustomerID { get; set; }
        [DataMember]
        public Nullable<int> SalesPersonID { get; set; }
        [DataMember]
        public Nullable<int> TerritoryID { get; set; }
        [DataMember]
        public int BillToAddressID { get; set; }
        [DataMember]
        public int ShipToAddressID { get; set; }
        [DataMember]
        public int ShipMethodID { get; set; }
        [DataMember]
        public Nullable<int> CreditCardID { get; set; }
        [DataMember]
        [Display(Name = "CC Approval Code")]
        public string CreditCardApprovalCode { get; set; }
        [DataMember]
        public Nullable<int> CurrencyRateID { get; set; }
        [DataMember]
        [Display(Name = "Subtotal")]
        public decimal SubTotal { get; set; }
        [DataMember]
        [Display(Name = "Tax Amount")]
        public decimal TaxAmt { get; set; }
        [DataMember]
        [Display(Name = "Freight")]
        public decimal Freight { get; set; }
        [DataMember]
        [Display(Name = "Total Due")]
        public decimal TotalDue { get; set; }
        [DataMember]
        public string Comment { get; set; }
        public System.Guid rowguid { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual ShipMethod ShipMethod { get; set; }
        public virtual CreditCard CreditCard { get; set; }
        public virtual CurrencyRate CurrencyRate { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; }
        public virtual SalesPerson SalesPerson { get; set; }
        public virtual SalesTerritory SalesTerritory { get; set; }
        public virtual ICollection<SalesOrderHeaderSalesReason> SalesOrderHeaderSalesReasons { get; set; }
    }
}
