//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorks.Domain.ModelObjects.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
    
    [DataContract]
    public partial class Vendor
    {
        public Vendor()
        {
            this.ProductVendors = new HashSet<ProductVendor>();
            this.PurchaseOrderHeaders = new HashSet<PurchaseOrderHeader>();
        }
    
        [DataMember]
        public int BusinessEntityID { get; set; }
        [DataMember]
        [Display(Name = "Account Number")]
        public string AccountNumber { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        [Display(Name = "Credit Rating")]
        public byte CreditRating { get; set; }
        [DataMember]
        [Display(Name = "Preferred Vendor Status")]
        public bool PreferredVendorStatus { get; set; }
        [DataMember]
        [Display(Name = "Active Flag")]
        public bool ActiveFlag { get; set; }
        [DataMember]
        [Display(Name = "Purchasing Web Service URL")]
        public string PurchasingWebServiceURL { get; set; }
        [Display(Name = "Modified Date")]
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual BusinessEntity BusinessEntity { get; set; }
        public virtual ICollection<ProductVendor> ProductVendors { get; set; }
        public virtual ICollection<PurchaseOrderHeader> PurchaseOrderHeaders { get; set; }
    }
}
